apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
  name: elasticsearch-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1651678504615-8081-dobs.csi.digitalocean.com
    volumeHandle: 9ccd6161-d024-11ec-ae91-0a58ac14b73e
  persistentVolumeReclaimPolicy: Delete
  storageClassName: do-block-storage
  volumeMode: Filesystem
status: {}